# Generated by Django 2.1.7 on 2019-03-28 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='number',
            field=models.IntegerField(default=27, verbose_name='Номер'),
            preserve_default=False,
        ),
    ]
