# Generated by Django 2.1.7 on 2019-03-28 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cams', '0003_camera_rtsp_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='cam_type',
            field=models.CharField(choices=[('out', 'Наружняя'), ('in', 'Внутренняя')], default='out', max_length=3, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='mask',
            field=models.CharField(choices=[('G%s_P%sC%s', 'G(дом)_P(подъезд)C(номер)'), ('G%s_F%s', 'G(дом)_F(номер)')], default='G%s_P%sC%s', max_length=100, verbose_name='Маска'),
        ),
    ]
